{
    'name': 'eZee Optimus POS Integration',
    'version': '19.0.1.1.0',
    'summary': 'One-way sync from eZee Optimus POS to Odoo 19',
    'author': 'Dubaiincario',
    'category': 'Accounting',
    'license': 'LGPL-3',
    'depends': ['account', 'accountant'],
    'data': [
        'security/ezee_optimus_groups.xml',
        'security/ir.model.access.csv',
        'data/demo_data.xml',
        'views/account_move_views.xml',
        'views/ezee_optimus_menus.xml',
        'views/ezee_optimus_fas_config_views.xml',
        'views/ezee_optimus_outlet_views.xml',
        'views/ezee_optimus_mapping_views.xml',
        'views/ezee_optimus_tax_mapping_views.xml',
        'views/ezee_optimus_sync_log_views.xml',
        'wizards/ezee_optimus_manual_sync_wizard_views.xml',
        'views/ezee_optimus_sync_views.xml',
        'data/ir_cron_data.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
